"use client";
import { useState, useEffect } from "react";
import Link from "next/link";

const C = {
  dark:  { bg:"#090909", card:"#111113", surface:"#141416", border:"#333336", text:"#F0F0F0", muted:"#7A7A80", green:"#00E676" },
  light: { bg:"#F7F7F5", card:"#FFFFFF",  surface:"#EEEEED", border:"#BABAB8", text:"#0A0A0A", muted:"#606065", green:"#008A38" },
};
const gs = "'Google Sans Flex','DM Sans',sans-serif";
const ns = "'Noto Serif',Georgia,serif";
const pf = "'Playfair Display',Georgia,serif";

const SECTIONS = [
  {
    n: "1. Acceptance",
    body: "By accessing or using Clarinvest (clarinvest.app), you agree to these Terms of Service. If you do not agree, do not use the platform. These terms apply to all users, including free trial users and paying subscribers.",
  },
  {
    n: "2. The Service",
    body: "Clarinvest provides AI-generated financial analysis, screening tools, and portfolio utilities for informational purposes. The platform is operated by Clarinvest Ltd, incorporated in England and Wales.",
  },
  {
    n: "3. Not Financial Advice",
    body: "All content, analysis, scores, signals, and outputs generated by Clarinvest are for informational and educational purposes only. Clarinvest is not a regulated financial adviser, investment firm, or broker-dealer. Nothing on this platform constitutes financial advice, investment advice, tax advice, or a recommendation to buy, sell, or hold any asset, including stocks, indexes, ETFs, commodities, or any other financial instrument.\n\nAI-generated analysis is produced by automated systems and has not been reviewed or verified by a qualified human analyst. Analysis outputs may be incomplete, inaccurate, or out of date at the time you read them. Market conditions can change rapidly and without warning.\n\nYou are solely responsible for any investment decisions you make. Always conduct your own due diligence and consult a qualified, independent financial adviser before making any investment decision. Clarinvest Ltd accepts no responsibility or liability for financial losses arising from the use of, or reliance on, any platform content.",
  },
  {
    n: "4. Subscriptions and Billing",
    body: "Clarinvest offers three paid subscription plans: Essential, Pro, and Ultimate. Subscriptions renew automatically at the end of each billing period (monthly or annual). You may cancel at any time via your Account page; access continues until the end of the paid period. Prices are shown in your local currency and include applicable taxes where required. Payments are processed securely by Stripe. We do not store card details.",
  },
  {
    n: "5. Acceptable Use",
    body: "You may not use Clarinvest to redistribute, resell, or sublicense AI-generated analysis; scrape or bulk-download data; impersonate another user; or attempt to reverse-engineer or disrupt the platform. Accounts found in breach may be suspended without refund.",
  },
  {
    n: "6. Intellectual Property",
    body: "All platform content, branding, design, and AI-generated analysis belong to Clarinvest Ltd or its licensors. You may use analysis outputs for personal, non-commercial research only. Redistribution in any form requires written permission.",
  },
  {
    n: "7. Data and Privacy",
    body: "Your use of personal data is governed by our Privacy Policy. By using Clarinvest you consent to data processing as described there.",
  },
  {
    n: "8. Disclaimer of Warranties",
    body: "The platform is provided \"as is\" and \"as available\" without warranty of any kind, express or implied. We make no warranties, representations, or guarantees regarding: the accuracy, completeness, timeliness, or fitness for purpose of any content, analysis, or market data; the uninterrupted or error-free operation of the platform; the results that may be obtained from using the platform; or the accuracy, reliability, or suitability of any AI-generated analysis or score.\n\nMarket data is sourced from third-party providers and may contain errors, omissions, or delays beyond our control. AI-generated analysis is produced by automated systems and may be incorrect, incomplete, or misleading. Use of the platform and any reliance on its content is entirely at your own risk.",
  },
  {
    n: "9. Limitation of Liability",
    body: "To the fullest extent permitted by applicable law, Clarinvest Ltd and its directors, employees, and agents shall not be liable for: any investment losses or financial decisions made in reliance on platform content; any direct, indirect, incidental, special, consequential, or punitive damages arising from use of or inability to use the service; any loss of data, revenue, profits, or business opportunity; or any claims arising from errors, inaccuracies, or delays in market data or AI-generated analysis.\n\nIn jurisdictions where the exclusion of liability for negligence is not permitted, our liability is limited to the maximum extent permitted by law. Where liability cannot be fully excluded, our total liability to you for any claim is capped at the total subscription fees paid by you in the 12 months preceding the event giving rise to the claim.\n\nYou acknowledge that Clarinvest is an information tool only and that all investment decisions are made entirely at your own discretion and risk.",
  },
  {
    n: "10. Modifications",
    body: "We may update these terms at any time. Material changes will be communicated by email or platform notification. Continued use after changes constitutes acceptance.",
  },
  {
    n: "11. Governing Law",
    body: "These terms are governed by the laws of England and Wales. Any disputes are subject to the exclusive jurisdiction of the courts of England and Wales.",
  },
  {
    n: "12. Contact",
    body: "For questions about these terms, contact us at support@clarinvest.app.",
  },
];

export default function TermsPage() {
  const [mode, setMode] = useState("dark");

  useEffect(() => {
    try {
      const saved = localStorage.getItem("clarinvest-theme");
      if (saved === "light" || saved === "dark") setMode(saved);
    } catch {}
  }, []);

  function toggleMode() {
    const next = mode === "dark" ? "light" : "dark";
    setMode(next);
    try { localStorage.setItem("clarinvest-theme", next); } catch {}
  }

  const c = C[mode];

  return (
    <div style={{ background: c.bg, minHeight: "100vh", color: c.text, fontFamily: gs }}>

      {/* Nav */}
      <nav style={{
        position: "sticky", top: 0, zIndex: 100,
        borderBottom: `1px solid ${c.border}`,
        background: mode === "dark" ? "rgba(9,9,9,0.92)" : "rgba(247,247,245,0.92)",
        backdropFilter: "blur(16px)",
        padding: "0 2.5rem", height: "58px",
        display: "flex", alignItems: "center", justifyContent: "space-between",
      }}>
        <Link href="/" style={{ textDecoration: "none" }}>
          <span style={{ fontFamily: pf, fontSize: "1rem", fontWeight: 600, letterSpacing: "0.03em", color: c.text }}>
            CLARINVEST
          </span>
        </Link>
        <div style={{ display: "flex", alignItems: "center", gap: "1rem" }}>
          <Link href="/privacy" style={{ fontFamily: gs, fontSize: "0.8rem", color: c.muted, textDecoration: "none" }}>Privacy</Link>
          <button onClick={toggleMode} style={{
            background: "transparent", border: `1px solid ${c.border}`,
            borderRadius: "50px", padding: "5px 14px", cursor: "pointer",
            fontFamily: gs, fontSize: "0.75rem", color: c.muted,
          }}>
            {mode === "dark" ? "Light" : "Dark"}
          </button>
        </div>
      </nav>

      {/* Content */}
      <main style={{ maxWidth: "680px", margin: "0 auto", padding: "4rem 2rem 6rem" }}>

        {/* Header */}
        <div style={{ marginBottom: "3rem" }}>
          <p style={{ fontFamily: gs, fontSize: "0.68rem", letterSpacing: "0.18em", textTransform: "uppercase", fontWeight: 500, color: c.muted, marginBottom: "1rem" }}>
            Legal
          </p>
          <h1 style={{ fontFamily: ns, fontSize: "clamp(2rem,5vw,2.8rem)", fontWeight: 700, lineHeight: 1.15, marginBottom: "0.75rem" }}>
            Terms of Service
          </h1>
          <p style={{ fontFamily: gs, fontSize: "0.9rem", color: c.muted, lineHeight: 1.7 }}>
            Effective date: 1 June 2026. These terms govern your use of Clarinvest. Please read them carefully.
          </p>
        </div>

        {/* Disclaimer callout */}
        <div style={{
          background: `${c.green}10`, border: `1px solid ${c.green}40`,
          borderRadius: "10px", padding: "1rem 1.25rem", marginBottom: "3rem",
        }}>
          <p style={{ fontFamily: gs, fontSize: "0.82rem", color: c.green, lineHeight: 1.65, fontWeight: 500 }}>
            For informational purposes only. Not financial advice. Clarinvest does not provide regulated financial advice. Always consult a qualified financial adviser before making investment decisions.
          </p>
        </div>

        {/* Sections */}
        {SECTIONS.map((s, i) => (
          <div key={i} style={{ marginBottom: "2.5rem", paddingBottom: "2.5rem", borderBottom: i < SECTIONS.length - 1 ? `1px solid ${c.border}` : "none" }}>
            <h2 style={{ fontFamily: ns, fontSize: "1.15rem", fontWeight: 700, marginBottom: "0.9rem", color: c.text }}>
              {s.n}
            </h2>
            {s.body.split("\n\n").map((para, j) => (
              <p key={j} style={{ fontFamily: gs, fontSize: "0.92rem", lineHeight: 1.75, color: mode === "dark" ? c.muted : "#3A3A40", marginBottom: j < s.body.split("\n\n").length - 1 ? "1rem" : 0 }}>
                {para}
              </p>
            ))}
          </div>
        ))}

        {/* Footer note */}
        <p style={{ fontFamily: gs, fontSize: "0.78rem", color: c.muted, lineHeight: 1.7, textAlign: "center", marginTop: "3rem" }}>
          These terms were last updated on 1 June 2026. We recommend reviewing them periodically.
        </p>
      </main>

      {/* Page footer */}
      <footer style={{
        borderTop: `1px solid ${c.border}`, padding: "1.5rem 2.5rem",
        display: "flex", justifyContent: "space-between", alignItems: "center",
        flexWrap: "wrap", gap: "0.75rem",
      }}>
        <span style={{ fontFamily: gs, fontSize: "0.78rem", color: c.muted }}>© 2026 Clarinvest</span>
        <div style={{ display: "flex", gap: "1.5rem" }}>
          <Link href="/" style={{ fontFamily: gs, fontSize: "0.78rem", color: c.muted, textDecoration: "none" }}>Home</Link>
          <Link href="/privacy" style={{ fontFamily: gs, fontSize: "0.78rem", color: c.muted, textDecoration: "none" }}>Privacy</Link>
        </div>
        <span style={{ fontFamily: gs, fontSize: "0.78rem", color: c.muted }}>For informational purposes only. Not financial advice.</span>
      </footer>

    </div>
  );
}